x =7

print(x)

#Indentation is important in python

y=10
name="Space"

print(x>5)
y=11
print(y)

y==11

'Foobar'<= 'Foobar'

zxc = input("Pls enter something")

print(zxc)


while x>=5:
    x=x+1
    if x>1000:
        break


level = int(input("Enter your level"))
#cast to int
if level==99:
    print ("MaxLevel")
else:
    print ("Train more pls?")


casttofloat = float(input("Enter number:"))
print(casttofloat)











x="Theendfewadawsdawjkhuiy7867w32giurkbjtg ,,.trl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawjtrl3wkjiou8yoiafabacdewadadawkdjakjdiajidjiajdijdiawj"
for str in x:
    print(str)

    #interate over string x








































